dist: xenial
language: python
matrix:
  include:
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37
    - python: '3.8'
      env: TOXENV=py38
install:
  - pip install tox codecov
script:
  - tox -v
after_success:
  - codecov --file .tox/3.6/log/coverage.xml
deploy:
  provider: pypi
  user: TimofeyKukushkin
  password:
    secure: eYYxSNQ112txSsSvKqHLbDDWpfKcKz+b1ejkikX0XylB1dFgMEc97H8Xc2Hhd96czS0ty/U4G45yZX2UulpmimDEbPxsvS4oIDSDZCLXHjcVBNopvbo2ClapLJoDxaKuPKVrPrYQxJsaWTvc3TL9crI/gIrGUG80dlQkL2E9QWJNuIs3Q5HN4LdxiZpW5Y2MDxjtu5yq8bh09pPv2xkObFAwqUDqmAVs1g9v7BvsZbvTgM6rO9+EtHBywol2raZjfXzTo86Czn/1SMdXKHdmDRFP/6k98mY4oeakGCSEkdUy67JVXozatc9oLHWh+/x90y8YF//CpWjYCCZpkpaWMmuU8OXw28XklItogJ7gPjT6ww7PEo53oTzMBwsdaYntKDYLSuWVMLZdbqV01JpeQRcHfJOqKeambCdPvcWZKXOLEiJAbnlgMZ0RAdEBABXWLdkhKYMvFcItXaePcXOYu0sdkGwpxqEwQ+fnx2nRhu5LZNKwU5V/oNvmO0l45YcEpEd/iKBztsKaJnujIPeSqJfV0X1Hqh7IvIhMXmBcVXPAiiYchEzZTrokiSECZhwSupBUUr2aZAMb4IvrWKjNvQtWLFsImadFY51RP3CGtMXJQJDmbmugGrrXXrT3jtLp0DUpewHdabybOQwmMejbd25N94mgNayd52dg8qwDnzA=
  on:
    tags: true
    python: '3.6'
  distributions: sdist bdist_wheel
  skip_existing: true
